import { CardItem } from '../types/card-item.type';

const CARDS: CardItem[] = [
  {
    cardName: "The Wolven King's Bite",
    rewardName: "Rigwald's Quills",
    corrupted: false,
    itemClass: 3,
    links: 0,
    gemLevel: 0,
  },
  {
    cardName: 'The Doctor',
    rewardName: 'Headhunter',
    corrupted: false,
    itemClass: 3,
    links: 0,
    gemLevel: 0,
  },
  {
    cardName: 'The Wind',
    rewardName: 'Windripper',
    corrupted: false,
    itemClass: 3,
    links: 0,
    gemLevel: 0,
  },
  {
    cardName: 'The Last One Standing',
    rewardName: "Atziri's Disfavour",
    corrupted: false,
    itemClass: 3,
    links: 0,
    gemLevel: 0,
  },
  {
    cardName: "The King's Heart",
    rewardName: "Kaom's Heart",
    corrupted: false,
    itemClass: 3,
    links: 0,
    gemLevel: 0,
  },
  {
    cardName: 'The Master',
    rewardName: "Bisco's Collar",
    corrupted: false,
    itemClass: 3,
    links: 0,
    gemLevel: 0,
  },
  {
    cardName: 'The Nurse',
    rewardName: 'The Doctor',
    corrupted: false,
    itemClass: 6,
    links: 0,
    gemLevel: 0,
  },
  {
    cardName: 'The Patient',
    rewardName: 'The Nurse',
    corrupted: false,
    itemClass: 6,
    links: 0,
    gemLevel: 0,
  },
  {
    cardName: 'The Spark and the Flame',
    rewardName: "Berek's Respite",
    corrupted: false,
    itemClass: 3,
    links: 0,
    gemLevel: 0,
  },
  {
    cardName: 'A Dab of Ink',
    rewardName: "The Poet's Pen",
    corrupted: false,
    itemClass: 3,
    links: 0,
    gemLevel: 0,
  },
  {
    cardName: 'The World Eater',
    rewardName: 'Starforge',
    corrupted: false,
    itemClass: 3,
    links: 0,
    gemLevel: 0,
  },
  {
    cardName: "Hunter's Reward",
    rewardName: 'The Taming',
    corrupted: false,
    itemClass: 3,
    links: 0,
    gemLevel: 0,
  },
  {
    cardName: 'The Immortal',
    rewardName: 'House of Mirrors',
    corrupted: false,
    itemClass: 6,
    links: 0,
    gemLevel: 0,
  },
  {
    cardName: 'The Queen',
    rewardName: "Atziri's Acuity",
    corrupted: false,
    itemClass: 3,
    links: 0,
    gemLevel: 0,
  },
  {
    cardName: 'The Fiend',
    rewardName: 'Headhunter',
    corrupted: true,
    itemClass: 3,
    links: 0,
    gemLevel: 0,
  },
  {
    cardName: 'Pride Before the Fall',
    rewardName: "Kaom's Heart",
    corrupted: true,
    itemClass: 3,
    links: 0,
    gemLevel: 0,
  },
  {
    cardName: 'The Throne',
    rewardName: "Kaom's Roots",
    corrupted: true,
    itemClass: 3,
    links: 0,
    gemLevel: 0,
  },
  {
    cardName: 'The Beast',
    rewardName: 'Belly of the Beast',
    corrupted: false,
    itemClass: 3,
    links: 0,
    gemLevel: 0,
  },
  {
    cardName: 'The Offering',
    rewardName: "Shavronne's Wrappings",
    corrupted: false,
    itemClass: 3,
    links: 0,
    gemLevel: 0,
  },
  {
    cardName: 'Burning Blood',
    rewardName: "Xoph's Blood",
    corrupted: true,
    itemClass: 3,
    links: 0,
    gemLevel: 0,
  },
  {
    cardName: 'Vanity',
    rewardName: 'Tabula Rasa',
    corrupted: true,
    itemClass: 3,
    links: 6,
    gemLevel: 0,
  },
  {
    cardName: 'The Life Thief',
    rewardName: "Zerphi's Heart",
    corrupted: false,
    itemClass: 3,
    links: 0,
    gemLevel: 0,
  },
  {
    cardName: "The Dragon's Heart",
    rewardName: 'Empower Support',
    corrupted: true,
    itemClass: 4,
    links: 0,
    gemLevel: 4,
  },
  {
    cardName: 'Wealth and Power',
    rewardName: 'Enlighten Support',
    corrupted: true,
    itemClass: 4,
    links: 0,
    gemLevel: 4,
  },
  {
    cardName: 'The Enlightened',
    rewardName: 'Enlighten Support',
    corrupted: false,
    itemClass: 4,
    links: 0,
    gemLevel: 3,
  },
  {
    cardName: 'The Artist',
    rewardName: 'Enhance Support',
    corrupted: true,
    itemClass: 4,
    links: 0,
    gemLevel: 4,
  },
  {
    cardName: 'Succor of the Sinless',
    rewardName: 'Bottled Faith',
    corrupted: false,
    itemClass: 3,
    links: 0,
    gemLevel: 0,
  },
  {
    cardName: 'The One That Got Away',
    rewardName: 'Replica Bated Breath',
    corrupted: false,
    itemClass: 3,
    links: 0,
    gemLevel: 0,
  },
  {
    cardName: 'The Academic',
    rewardName: 'Inspired Learning',
    corrupted: false,
    itemClass: 3,
    links: 0,
    gemLevel: 0,
  },
];

export default CARDS;
