export type ItemOverviewBaseType =
  | 'Abyssal Axe'
  | 'Agate Amulet'
  | 'Amber Amulet'
  | 'Ambush Mitts'
  | 'Ambusher'
  | 'Amethyst Ring'
  | 'Ancient Gauntlets'
  | 'Ancient Greaves'
  | 'Ancient Spirit Shield'
  | 'Antique Greaves'
  | 'Arcanist Gloves'
  | 'Arcanist Slippers'
  | 'Archon Kite Shield Piece'
  | 'Archon Kite Shield'
  | 'Assassin Bow'
  | 'Astral Plate'
  | 'Auric Mace'
  | 'Aventail Helmet'
  | 'Barbute Helmet'
  | 'Baroque Round Shield'
  | 'Basket Rapier'
  | 'Bastard Sword'
  | 'Black Maw Talisman'
  | 'Blazing Arrow Quiver'
  | 'Blinder'
  | 'Blood Raiment'
  | 'Blood Sceptre'
  | 'Blue Pearl Amulet'
  | 'Blunt Arrow Quiver Piece'
  | 'Blunt Arrow Quiver'
  | 'Bone Armour'
  | 'Bone Bow'
  | 'Bone Circlet'
  | 'Bone Helmet'
  | 'Boot Knife'
  | 'Branded Kite Shield'
  | 'Brass Maul'
  | 'Brass Spirit Shield'
  | 'Broadhead Arrow Quiver'
  | 'Bronze Gauntlets'
  | 'Bronze Sceptre'
  | 'Bronzescale Boots'
  | 'Bronzescale Gauntlets'
  | 'Buckskin Tunic'
  | 'Butcher Axe'
  | 'Callous Mask Piece'
  | 'Callous Mask'
  | 'Cardinal Round Shield'
  | 'Carnal Armour'
  | 'Carnal Boots'
  | 'Carnal Mitts'
  | 'Carnal Sceptre'
  | 'Carved Wand'
  | 'Cedar Tower Shield'
  | 'Chain Belt'
  | 'Chain Gloves'
  | 'Champion Kite Shield'
  | 'Chiming Spirit Shield'
  | 'Citadel Bow'
  | 'Citrine Amulet'
  | 'Clasped Boots'
  | 'Clasped Mitts'
  | 'Cleaver'
  | 'Close Helmet'
  | 'Cloth Belt Piece'
  | 'Cloth Belt'
  | 'Clutching Talisman'
  | 'Coiled Staff'
  | 'Colossal Tower Shield'
  | 'Compound Spiked Shield'
  | 'Conjurer Boots'
  | 'Conjurer Gloves'
  | 'Conquest Chainmail'
  | 'Copper Plate'
  | 'Coral Amulet'
  | 'Coral Ring'
  | 'Coronal Leather'
  | 'Corrugated Buckler'
  | 'Corsair Sword'
  | 'Crimson Round Shield'
  | 'Crude Bow'
  | 'Crusader Boots'
  | 'Crusader Chainmail'
  | 'Crusader Gloves'
  | 'Crusader Plate'
  | 'Crystal Belt'
  | 'Crystal Sceptre'
  | 'Crystal Wand'
  | 'Cutlass'
  | 'Death Bow'
  | 'Decimation Bow'
  | 'Deerskin Boots'
  | 'Deerskin Gloves'
  | 'Deicide Mask'
  | 'Demon Dagger'
  | 'Desert Brigandine'
  | 'Despot Axe'
  | 'Destiny Leather'
  | 'Destroyer Regalia'
  | 'Diamond Ring'
  | 'Dragonscale Boots'
  | 'Dragonscale Gauntlets'
  | 'Dread Maul'
  | 'Dream Mace'
  | 'Driftwood Wand'
  | 'Dusk Blade'
  | 'Ebony Tower Shield'
  | 'Eelskin Gloves'
  | 'Elder Sword'
  | 'Elegant Ringmail'
  | 'Elegant Round Shield'
  | 'Elegant Sword'
  | 'Embroidered Gloves'
  | 'Enameled Buckler'
  | 'Engraved Wand'
  | 'Estoc'
  | 'Etched Greatsword'
  | 'Eternal Burgonet'
  | 'Eternal Sword'
  | 'Exquisite Leather'
  | 'Ezomyte Axe'
  | 'Ezomyte Blade'
  | 'Ezomyte Burgonet'
  | 'Ezomyte Dagger'
  | 'Ezomyte Spiked Shield'
  | 'Ezomyte Staff'
  | 'Ezomyte Tower Shield'
  | 'Feathered Arrow Quiver'
  | 'Festival Mask'
  | 'Fiend Dagger'
  | 'Fingerless Silk Gloves'
  | 'Flaying Knife'
  | 'Fluted Bascinet'
  | 'Fugitive Boots'
  | 'Full Dragonscale'
  | 'Full Wyrmscale'
  | 'Gavel'
  | 'Gemstone Sword'
  | 'Gilded Sallet'
  | 'Gladiator Plate'
  | 'Gladius'
  | 'Glorious Plate'
  | 'Gnarled Branch'
  | 'Goathide Boots'
  | 'Goathide Gloves'
  | 'Gold Amulet'
  | 'Gold Ring'
  | 'Golden Buckler'
  | 'Golden Mask'
  | 'Golden Plate'
  | 'Goliath Gauntlets'
  | 'Goliath Greaves'
  | 'Great Crown'
  | 'Great Helmet'
  | 'Great Mallet'
  | 'Greatwolf Talisman'
  | 'Grinning Fetish'
  | 'Gut Ripper'
  | 'Harbinger Bow'
  | 'Harlequin Mask'
  | 'Harmonic Spirit Shield'
  | 'Headsman Axe'
  | 'Heavy Arrow Quiver'
  | 'Heavy Belt'
  | 'Highborn Staff'
  | 'Highland Blade'
  | 'Holy Chainmail'
  | 'Hubris Circlet'
  | 'Hydrascale Boots'
  | 'Hydrascale Gauntlets'
  | 'Imperial Bow'
  | 'Imperial Claw'
  | 'Imperial Maul'
  | 'Imperial Skean'
  | 'Imperial Staff Piece'
  | 'Imperial Staff'
  | 'Infernal Axe'
  | 'Infernal Sword'
  | 'Iron Circlet'
  | 'Iron Gauntlets'
  | 'Iron Hat'
  | 'Iron Mask'
  | 'Iron Ring'
  | 'Iron Staff'
  | 'Ironscale Boots'
  | 'Ironscale Gauntlets'
  | 'Jade Amulet'
  | 'Jagged Foil'
  | 'Jagged Maul'
  | 'Jasper Chopper'
  | 'Jewelled Foil'
  | 'Jingling Spirit Shield'
  | 'Judgement Staff'
  | 'Karui Chopper'
  | 'Karui Maul'
  | 'Karui Sceptre'
  | 'Labrys'
  | 'Lacewood Spirit Shield'
  | 'Lacquered Buckler'
  | 'Lacquered Garb'
  | 'Lacquered Helmet'
  | 'Laminated Kite Shield'
  | 'Lapis Amulet'
  | 'Lathi'
  | 'Latticed Ringmail'
  | 'Leather Belt'
  | 'Leather Cap'
  | 'Leather Hood'
  | 'Legion Boots'
  | 'Legion Gloves'
  | 'Legion Sword Piece'
  | 'Legion Sword'
  | 'Lion Pelt'
  | 'Lion Sword'
  | 'Long Bow'
  | 'Lunaris Circlet'
  | 'Maelström Staff'
  | 'Magistrate Crown'
  | 'Marble Amulet'
  | 'Meatgrinder'
  | 'Mesh Boots'
  | 'Mesh Gloves'
  | 'Military Staff'
  | 'Mind Cage'
  | 'Mirrored Spiked Shield'
  | 'Moonstone Ring'
  | 'Mosaic Kite Shield'
  | 'Murder Boots'
  | 'Murder Mitts'
  | 'Nailed Fist'
  | 'Necromancer Circlet'
  | 'Necromancer Silks'
  | 'Nightmare Bascinet'
  | 'Nightmare Mace'
  | 'Nubuck Boots'
  | 'Nubuck Gloves'
  | 'Onyx Amulet'
  | 'Opal Ring'
  | 'Opal Wand'
  | 'Ornate Mace'
  | 'Ornate Quiver'
  | 'Ornate Ringmail'
  | 'Ornate Sword'
  | 'Painted Buckler'
  | 'Painted Tower Shield'
  | 'Paua Amulet'
  | 'Paua Ring'
  | 'Penetrating Arrow Quiver'
  | 'Pine Buckler'
  | 'Pinnacle Tower Shield'
  | 'Plague Mask'
  | 'Plank Kite Shield'
  | 'Plate Vest'
  | 'Plated Greaves'
  | 'Platinum Sceptre'
  | 'Poleaxe'
  | 'Polished Spiked Shield'
  | 'Praetor Crown'
  | 'Primal Arrow Quiver'
  | 'Primordial Staff'
  | 'Prismatic Ring'
  | 'Prophecy Wand'
  | 'Prophet Crown'
  | 'Quarterstaff'
  | 'Quartz Wand'
  | 'Ranger Bow'
  | 'Raven Mask'
  | 'Rawhide Boots'
  | 'Rawhide Tower Shield'
  | 'Reaver Sword'
  | 'Recurve Bow'
  | 'Regicide Mask'
  | 'Reinforced Greaves'
  | 'Reinforced Tower Shield'
  | 'Ring'
  | 'Ritual Sceptre'
  | 'Riveted Boots'
  | 'Riveted Gloves'
  | 'Rock Breaker'
  | 'Rotfeather Talisman'
  | 'Rotted Round Shield'
  | 'Royal Bow'
  | 'Royal Burgonet'
  | 'Royal Skean'
  | 'Royal Staff'
  | 'Ruby Ring'
  | 'Runic Crown'
  | 'Runic Gages'
  | 'Runic Gauntlets'
  | 'Runic Helm'
  | 'Runic Sabatons'
  | 'Runic Sollerets'
  | 'Rustic Sash'
  | 'Sacrificial Garb'
  | 'Sadist Garb'
  | 'Sage Wand'
  | 'Saintly Chainmail'
  | 'Samite Gloves'
  | 'Samnite Helmet'
  | 'Sapphire Ring'
  | 'Satin Gloves'
  | 'Scholar Boots'
  | 'Secutor Helm'
  | 'Sentinel Jacket'
  | 'Serpentine Staff'
  | 'Serpentscale Boots'
  | 'Serpentscale Gauntlets'
  | 'Serrated Arrow Quiver'
  | 'Shadow Axe'
  | 'Shadow Sceptre'
  | 'Shagreen Boots'
  | 'Shagreen Gloves'
  | 'Sharkskin Boots'
  | 'Sharkskin Tunic'
  | 'Sharktooth Arrow Quiver'
  | 'Short Bow'
  | 'Siege Axe'
  | 'Siege Helmet'
  | 'Silk Gloves'
  | 'Silk Slippers'
  | 'Silken Hood'
  | 'Silken Vest'
  | 'Simple Robe'
  | 'Sinner Tricorne'
  | 'Skinning Knife'
  | 'Slaughter Knife'
  | 'Sledgehammer'
  | 'Slink Boots'
  | 'Slink Gloves'
  | 'Solaris Circlet'
  | 'Soldier Boots'
  | 'Soldier Gloves'
  | 'Soldier Helmet'
  | 'Sorcerer Boots'
  | 'Sovereign Spiked Shield'
  | 'Spidersilk Robe'
  | 'Spike-Point Arrow Quiver'
  | 'Spiked Club'
  | 'Spiked Gloves'
  | 'Spine Bow'
  | 'Spiraled Wand'
  | 'Stealth Boots'
  | 'Steel Circlet'
  | 'Steel Gauntlets'
  | 'Steel Kite Shield'
  | 'Steel Ring'
  | 'Steelhead'
  | 'Steelscale Gauntlets'
  | 'Steelwood Bow'
  | 'Stiletto'
  | 'Strapped Boots'
  | 'Strapped Mitts'
  | 'Studded Belt'
  | 'Studded Round Shield'
  | 'Stygian Vise'
  | 'Sun Leather'
  | 'Supreme Spiked Shield'
  | 'Tarnished Spirit Shield'
  | 'Teak Round Shield'
  | 'Terror Claw'
  | 'Terror Maul'
  | 'Thorium Spirit Shield'
  | 'Thresher Claw'
  | 'Tiger Sword'
  | 'Timeworn Claw'
  | 'Titan Gauntlets'
  | 'Titan Greaves'
  | 'Titanium Spirit Shield'
  | 'Topaz Ring'
  | 'Tornado Wand'
  | 'Trapper Boots'
  | 'Tribal Circlet'
  | 'Tricorne'
  | 'Triumphant Lamellar'
  | 'Turquoise Amulet'
  | 'Two-Point Arrow Quiver'
  | 'Two-Stone Ring'
  | 'Two-Toned Boots'
  | 'Unset Amulet'
  | 'Unset Ring'
  | 'Ursine Pelt'
  | 'Vaal Axe'
  | 'Vaal Buckler'
  | 'Vaal Claw'
  | 'Vaal Gauntlets'
  | 'Vaal Hatchet'
  | 'Vaal Mask'
  | 'Vaal Rapier'
  | 'Vaal Regalia'
  | 'Vaal Sceptre'
  | 'Vaal Spirit Shield'
  | 'Vanguard Belt'
  | 'Varnished Coat'
  | 'Velvet Gloves'
  | 'Velvet Slippers'
  | 'Vile Arrow Quiver'
  | 'Vile Staff'
  | 'Vine Circlet'
  | 'Void Axe'
  | 'Void Sceptre'
  | 'War Buckler'
  | 'War Hammer'
  | 'War Sword'
  | 'Wereclaw Talisman'
  | 'Widowsilk Robe'
  | 'Wild Leather'
  | 'Wolf Pelt'
  | 'Woodsplitter'
  | 'Wool Gloves'
  | 'Wool Shoes'
  | 'Wrapped Mitts'
  | 'Wyrmscale Boots'
  | 'Wyrmscale Doublet'
  | 'Wyrmscale Gauntlets'
  | 'Zealot Gloves'
  | 'Zealot Helmet'
  | 'Zodiac Leather'
  | "Assassin's Boots"
  | "Assassin's Garb"
  | "Assassin's Mitts"
  | "Charan's Sword"
  | "Cutthroat's Garb"
  | "Goat's Horn"
  | "Hellion's Paw"
  | "Occultist's Vestment"
  | "Sage's Robe"
  | "Saint's Hauberk"
  | "Savant's Robe"
  | "Scholar's Robe";
