export interface CardItem {
  cardName: string;
  corrupted: boolean;
  gemLevel: number;
  itemClass: number;
  links: number;
  rewardName: string;
}

const CARDS: CardItem[] = [

const CARDS: CardItem[] = [
  {
    cardName: "The Wolven King's Bite",
    corrupted: false,
    gemLevel: 0,
    itemClass: 3,
    links: 0,
    rewardName: "Rigwald's Quills",
  },
  {
    cardName: 'The Doctor',
    corrupted: false,
    gemLevel: 0,
    itemClass: 3,
    links: 0,
    rewardName: 'Headhunter',
  },
  {
    cardName: 'The Wind',
    corrupted: false,
    gemLevel: 0,
    itemClass: 3,
    links: 0,
    rewardName: 'Windripper',
  },
  {
    cardName: 'The Last One Standing',
    corrupted: false,
    gemLevel: 0,
    itemClass: 3,
    links: 0,
    rewardName: "Atziri's Disfavour",
  },
  {
    cardName: "The King's Heart",
    corrupted: false,
    gemLevel: 0,
    itemClass: 3,
    links: 0,
    rewardName: "Kaom's Heart",
  },
  {
    cardName: 'The Master',
    corrupted: false,
    gemLevel: 0,
    itemClass: 3,
    links: 0,
    rewardName: "Bisco's Collar",
  },
  {
    cardName: 'The Nurse',
    corrupted: false,
    gemLevel: 0,
    itemClass: 6,
    links: 0,
    rewardName: 'The Doctor',
  },
  {
    cardName: 'The Patient',
    corrupted: false,
    gemLevel: 0,
    itemClass: 6,
    links: 0,
    rewardName: 'The Nurse',
  },
  {
    cardName: 'The Spark and the Flame',
    corrupted: false,
    gemLevel: 0,
    itemClass: 3,
    links: 0,
    rewardName: "Berek's Respite",
  },
  {
    cardName: 'A Dab of Ink',
    corrupted: false,
    gemLevel: 0,
    itemClass: 3,
    links: 0,
    rewardName: "The Poet's Pen",
  },
  {
    cardName: 'The World Eater',
    corrupted: false,
    gemLevel: 0,
    itemClass: 3,
    links: 0,
    rewardName: 'Starforge',
  },
  {
    cardName: "Hunter's Reward",
    corrupted: false,
    gemLevel: 0,
    itemClass: 3,
    links: 0,
    rewardName: 'The Taming',
  },
  {
    cardName: 'The Immortal',
    corrupted: false,
    gemLevel: 0,
    itemClass: 6,
    links: 0,
    rewardName: 'House of Mirrors',
  },
  {
    cardName: 'The Queen',
    corrupted: false,
    gemLevel: 0,
    itemClass: 3,
    links: 0,
    rewardName: "Atziri's Acuity",
  },
  {
    cardName: 'The Fiend',
    corrupted: true,
    gemLevel: 0,
    itemClass: 3,
    links: 0,
    rewardName: 'Headhunter',
  },
  {
    cardName: 'Pride Before the Fall',
    corrupted: true,
    gemLevel: 0,
    itemClass: 3,
    links: 0,
    rewardName: "Kaom's Heart",
  },
  {
    cardName: 'The Throne',
    corrupted: true,
    gemLevel: 0,
    itemClass: 3,
    links: 0,
    rewardName: "Kaom's Roots",
  },
  {
    cardName: 'The Beast',
    corrupted: false,
    gemLevel: 0,
    itemClass: 3,
    links: 0,
    rewardName: 'Belly of the Beast',
  },
  {
    cardName: 'The Offering',
    corrupted: false,
    gemLevel: 0,
    itemClass: 3,
    links: 0,
    rewardName: "Shavronne's Wrappings",
  },
  {
    cardName: 'Burning Blood',
    corrupted: true,
    gemLevel: 0,
    itemClass: 3,
    links: 0,
    rewardName: "Xoph's Blood",
  },
  {
    cardName: 'Vanity',
    corrupted: true,
    gemLevel: 0,
    itemClass: 3,
    links: 6,
    rewardName: 'Tabula Rasa',
  },
  {
    cardName: 'The Life Thief',
    corrupted: false,
    gemLevel: 0,
    itemClass: 3,
    links: 0,
    rewardName: "Zerphi's Heart",
  },
  {
    cardName: "The Dragon's Heart",
    corrupted: true,
    gemLevel: 4,
    itemClass: 4,
    links: 0,
    rewardName: 'Empower Support',
  },
  {
    cardName: 'Wealth and Power',
    corrupted: true,
    gemLevel: 4,
    itemClass: 4,
    links: 0,
    rewardName: 'Enlighten Support',
  },
  {
    cardName: 'The Enlightened',
    corrupted: false,
    gemLevel: 3,
    itemClass: 4,
    links: 0,
    rewardName: 'Enlighten Support',
  },
  {
    cardName: 'The Artist',
    corrupted: true,
    gemLevel: 4,
    itemClass: 4,
    links: 0,
    rewardName: 'Enhance Support',
  },
  {
    cardName: 'Succor of the Sinless',
    corrupted: false,
    gemLevel: 0,
    itemClass: 3,
    links: 0,
    rewardName: 'Bottled Faith',
  },
  {
    cardName: 'The One That Got Away',
    corrupted: false,
    gemLevel: 0,
    itemClass: 3,
    links: 0,
    rewardName: 'Replica Bated Breath',
  },
  {
    cardName: 'The Academic',
    corrupted: false,
    gemLevel: 0,
    itemClass: 3,
    links: 0,
    rewardName: 'Inspired Learning',
  },
];
export default CARDS;
