import { ItemClass } from '@domain/value-objects/item-class.enum';

export interface RawItemCardConfig {
  Name: string;
  Reward: string;
  Corrupted: boolean;
  iClass: number;
  Links: number;
  gemLevel: number;
}

export const cards: RawItemCardConfig[] = [{
  Name: "The Wolven King's Bite",
  Reward: "Rigwald's Quills",
  Corrupted: false,
  iClass: ItemClass.UNIQUE,
  Links: 0,
  gemLevel: 0,
}, {
  Name: 'The Doctor',
  Reward: 'Headhunter',
  Corrupted: false,
  iClass: ItemClass.UNIQUE,
  Links: 0,
  gemLevel: 0,
}, {
  Name: 'The Wind',
  Reward: 'Windripper',
  Corrupted: false,
  iClass: ItemClass.UNIQUE,
  Links: 0,
  gemLevel: 0,
}, {
  Name: "The King's Heart",
  Reward: "Kaom's Heart",
  Corrupted: false,
  iClass: ItemClass.UNIQUE,
  Links: 0,
  gemLevel: 0,
}, {
  Name: 'The Master',
  Reward: "Bisco's Collar",
  Corrupted: false,
  iClass: ItemClass.UNIQUE,
  Links: 0,
  gemLevel: 0,
}, {
  Name: 'The Nurse',
  Reward: 'The Doctor',
  Corrupted: false,
  iClass: ItemClass.DIVINATION_CARD,
  Links: 0,
  gemLevel: 0,
}, {
  Name: 'The Patient',
  Reward: 'The Nurse',
  Corrupted: false,
  iClass: ItemClass.DIVINATION_CARD,
  Links: 0,
  gemLevel: 0,
}, {
  Name: 'The Spark and the Flame',
  Reward: "Berek's Respite",
  Corrupted: false,
  iClass: ItemClass.UNIQUE,
  Links: 0,
  gemLevel: 0,
}, {
  Name: 'A Dab of Ink',
  Reward: "The Poet's Pen",
  Corrupted: false,
  iClass: ItemClass.UNIQUE,
  Links: 0,
  gemLevel: 0,
}, {
  Name: 'The World Eater',
  Reward: 'Starforge',
  Corrupted: false,
  iClass: ItemClass.UNIQUE,
  Links: 0,
  gemLevel: 0,
}, {
  Name: "Hunter's Reward",
  Reward: 'The Taming',
  Corrupted: false,
  iClass: ItemClass.UNIQUE,
  Links: 0,
  gemLevel: 0,
}, {
  Name: 'The Immortal',
  Reward: 'House of Mirrors',
  Corrupted: false,
  iClass: ItemClass.DIVINATION_CARD,
  Links: 0,
  gemLevel: 0,
}, {
  Name: 'The Queen',
  Reward: "Atziri's Acuity",
  Corrupted: false,
  iClass: ItemClass.UNIQUE,
  Links: 0,
  gemLevel: 0,
}, {
  Name: 'The Fiend',
  Reward: 'Headhunter',
  Corrupted: true,
  iClass: ItemClass.UNIQUE,
  Links: 0,
  gemLevel: 0,
}, {
  Name: 'The Throne',
  Reward: "Kaom's Roots",
  Corrupted: true,
  iClass: ItemClass.UNIQUE,
  Links: 0,
  gemLevel: 0,
}, {
  Name: 'The Beast',
  Reward: 'Belly of the Beast',
  Corrupted: false,
  iClass: ItemClass.UNIQUE,
  Links: 0,
  gemLevel: 0,
}, {
  Name: 'The Mayor',
  Reward: 'The Perandus Manor',
  Corrupted: false,
  iClass: ItemClass.UNIQUE,
  Links: 0,
  gemLevel: 0,
}, {
  Name: 'The Professor',
  Reward: 'The Putrid Cloister',
  Corrupted: false,
  iClass: ItemClass.UNIQUE,
  Links: 0,
  gemLevel: 0,
}, {
  Name: 'The Offering',
  Reward: "Shavronne's Wrappings",
  Corrupted: false,
  iClass: ItemClass.UNIQUE,
  Links: 0,
  gemLevel: 0,
}, {
  Name: 'The Vast',
  Reward: 'Song of the Sirens',
  Corrupted: false,
  iClass: ItemClass.UNIQUE,
  Links: 0,
  gemLevel: 0,
}, {
  Name: 'Burning Blood',
  Reward: "Xoph's Blood",
  Corrupted: true,
  iClass: ItemClass.UNIQUE,
  Links: 0,
  gemLevel: 0,
}, {
  Name: 'The Life Thief',
  Reward: "Zerphi's Heart",
  Corrupted: false,
  iClass: ItemClass.UNIQUE,
  Links: 0,
  gemLevel: 0,
}, {
  Name: "The Dragon's Heart",
  Reward: 'Empower Support',
  Corrupted: true,
  iClass: ItemClass.SKILL_GEM,
  Links: 0,
  gemLevel: 4,
}, {
  Name: 'Wealth and Power',
  Reward: 'Enlighten Support',
  Corrupted: true,
  iClass: ItemClass.SKILL_GEM,
  Links: 0,
  gemLevel: 4,
}, {
  Name: 'The Enlightened',
  Reward: 'Enlighten Support',
  Corrupted: false,
  iClass: ItemClass.SKILL_GEM,
  Links: 0,
  gemLevel: 3,
}, {
  Name: 'The Artist',
  Reward: 'Enhance Support',
  Corrupted: true,
  iClass: ItemClass.SKILL_GEM,
  Links: 0,
  gemLevel: 4,
}, {
  Name: 'Succor of the Sinless',
  Reward: 'Bottled Faith',
  Corrupted: false,
  iClass: ItemClass.UNIQUE,
  Links: 0,
  gemLevel: 0,
}, {
  Name: 'The One That Got Away',
  Reward: 'Replica Bated Breath',
  Corrupted: false,
  iClass: ItemClass.UNIQUE,
  Links: 0,
  gemLevel: 0,
}, {
  Name: 'The Academic',
  Reward: 'Inspired Learning',
  Corrupted: false,
  iClass: ItemClass.UNIQUE,
  Links: 0,
  gemLevel: 0,
}];
