module.exports = [
  {
    Name: "The Wolven King's Bite",
    Reward: "Rigwald's Quills",
    Corrupted: false,
    iClass: 3,
    Links: 0,
    gemLevel: 0,
  }, {
    Name: 'The Doctor',
    Reward: 'Headhunter',
    Corrupted: false,
    iClass: 3,
    Links: 0,
    gemLevel: 0,
  }, {
    Name: 'The Wind',
    Reward: 'Windripper',
    Corrupted: false,
    iClass: 3,
    Links: 0,
    gemLevel: 0,
  }, {
    Name: 'The Last One Standing',
    Reward: "Atziri's Disfavour",
    Corrupted: false,
    iClass: 3,
    Links: 0,
    gemLevel: 0,
  }, {
    Name: "The King's Heart",
    Reward: "Kaom's Heart",
    Corrupted: false,
    iClass: 3,
    Links: 0,
    gemLevel: 0,
  }, {
    Name: 'The Master',
    Reward: "Bisco's Collar",
    Corrupted: false,
    iClass: 3,
    Links: 0,
    gemLevel: 0,
  }, {
    Name: 'The Nurse',
    Reward: 'The Doctor',
    Corrupted: false,
    iClass: 6,
    Links: 0,
    gemLevel: 0,
  }, {
    Name: 'The Patient',
    Reward: 'The Nurse',
    Corrupted: false,
    iClass: 6,
    Links: 0,
    gemLevel: 0,
  }, {
    Name: 'The Spark and the Flame',
    Reward: "Berek's Respite",
    Corrupted: false,
    iClass: 3,
    Links: 0,
    gemLevel: 0,
  }, {
    Name: 'A Dab of Ink',
    Reward: "The Poet's Pen",
    Corrupted: false,
    iClass: 3,
    Links: 0,
    gemLevel: 0,
  }, {
    Name: 'The World Eater',
    Reward: 'Starforge',
    Corrupted: false,
    iClass: 3,
    Links: 0,
    gemLevel: 0,
  }, {
    Name: "Hunter's Reward",
    Reward: 'The Taming',
    Corrupted: false,
    iClass: 3,
    Links: 0,
    gemLevel: 0,
  }, {
    Name: 'The Immortal',
    Reward: 'House of Mirrors',
    Corrupted: false,
    iClass: 6,
    Links: 0,
    gemLevel: 0,
  }, {
    Name: 'The Queen',
    Reward: "Atziri's Acuity",
    Corrupted: false,
    iClass: 3,
    Links: 0,
    gemLevel: 0,
  }, {
    Name: 'The Fiend',
    Reward: 'Headhunter',
    Corrupted: true,
    iClass: 3,
    Links: 0,
    gemLevel: 0,
  }, {
    Name: 'Pride Before the Fall',
    Reward: "Kaom's Heart",
    Corrupted: true,
    iClass: 3,
    Links: 0,
    gemLevel: 0,
  }, {
    Name: 'The Throne',
    Reward: "Kaom's Roots",
    Corrupted: true,
    iClass: 3,
    Links: 0,
    gemLevel: 0,
  }, {
    Name: 'Beauty Through Death',
    Reward: "The Queen's Sacrifice",
    Corrupted: false,
    iClass: 8,
    Links: 0,
    gemLevel: 0,
  }, {
    Name: 'Immortal Resolve',
    Reward: 'Fated Connections',
    Corrupted: false,
    iClass: 8,
    Links: 0,
    gemLevel: 0,
  }, {
    Name: 'The Iron Bard',
    Reward: 'Trash to Treasure',
    Corrupted: false,
    iClass: 8,
    Links: 0,
    gemLevel: 0,
  }, {
    Name: 'The Valley of Steel Boxes',
    Reward: 'Monstrous Treasure',
    Corrupted: false,
    iClass: 8,
    Links: 0,
    gemLevel: 0,
  }, {
    Name: 'The Beast',
    Reward: 'Belly of the Beast',
    Corrupted: false,
    iClass: 3,
    Links: 0,
    gemLevel: 0,
  }, {
    Name: 'The Mayor',
    Reward: 'The Perandus Manor',
    Corrupted: false,
    iClass: 3,
    Links: 0,
    gemLevel: 0,
  }, {
    Name: 'The Professor',
    Reward: 'The Putrid Cloister',
    Corrupted: false,
    iClass: 3,
    Links: 0,
    gemLevel: 0,
  }, {
    Name: 'The Offering',
    Reward: "Shavronne's Wrappings",
    Corrupted: false,
    iClass: 3,
    Links: 0,
    gemLevel: 0,
  }, {
    Name: 'The Vast',
    Reward: 'Song of the Sirens',
    Corrupted: false,
    iClass: 3,
    Links: 0,
    gemLevel: 0,
  }, {
    Name: 'Burning Blood',
    Reward: "Xoph's Blood",
    Corrupted: true,
    iClass: 3,
    Links: 0,
    gemLevel: 0,
  }, {
    Name: 'Vanity',
    Reward: 'Tabula Rasa',
    Corrupted: true,
    iClass: 3,
    Links: 6,
    gemLevel: 0,
  }, {
    Name: 'The Life Thief',
    Reward: "Zerphi's Heart",
    Corrupted: false,
    iClass: 3,
    Links: 0,
    gemLevel: 0,
  }, {
    Name: "The Dragon's Heart",
    Reward: 'Empower Support',
    Corrupted: true,
    iClass: 4,
    Links: 0,
    gemLevel: 4,
  }, {
    Name: 'Wealth and Power',
    Reward: 'Enlighten Support',
    Corrupted: true,
    iClass: 4,
    Links: 0,
    gemLevel: 4,
  }, {
    Name: 'The Enlightened',
    Reward: 'Enlighten Support',
    Corrupted: false,
    iClass: 4,
    Links: 0,
    gemLevel: 3,
  }, {
    Name: 'The Artist',
    Reward: 'Enhance Support',
    Corrupted: true,
    iClass: 4,
    Links: 0,
    gemLevel: 4,
  }, {
    Name: 'Succor of the Sinless',
    Reward: 'Bottled Faith',
    Corrupted: false,
    iClass: 3,
    Links: 0,
    gemLevel: 0,
  }, {
    Name: 'The One That Got Away',
    Reward: 'Replica Bated Breath',
    Corrupted: false,
    iClass: 3,
    Links: 0,
    gemLevel: 0,
  }, {
    Name: 'The Academic',
    Reward: 'Inspired Learning',
    Corrupted: false,
    iClass: 3,
    Links: 0,
    gemLevel: 0,
  }
];
