export type ItemOverviewItemType =
  | 'Amulet'
  | 'Belt'
  | 'Body Armour'
  | 'Boots'
  | 'Bow'
  | 'Claw'
  | 'Dagger'
  | 'Gloves'
  | 'Helmet'
  | 'Jewel'
  | 'One Handed Axe'
  | 'One Handed Mace'
  | 'One Handed Sword'
  | 'Quiver'
  | 'Ring'
  | 'Shield'
  | 'Staff'
  | 'Two Handed Axe'
  | 'Two Handed Mace'
  | 'Two Handed Sword'
  | 'Wand';
