name: CI/CD Pipeline
on:
  push:
    branches: [ master ]
    
jobs:
  continuous-integration:
    name: CI/CD Pipeline
    strategy:
      matrix:
        node-version: [14.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: |
          npm ci
        env:
          CI: true
      # - name: generate .env file
      #   run: |
      #     echo 'FIREBASE_CLIENT_EMAIL="${{ secrets.FIREBASE_CLIENT_EMAIL }}"' >> .env |
      #     echo 'FIREBASE_PRIVATE_KEY="${{ secrets.FIREBASE_PRIVATE_KEY }}"' >> .env |
      #     echo 'FIREBASE_PROJECT_ID="${{ secrets.FIREBASE_PROJECT_ID }}"' >> .env
      - name: zip
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./bundle.zip package.json index.js ./config ./components ./node_modules .env
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2 
      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          aws lambda update-function-code \
          --function-name poe-cards \
          --zip-file fileb://bundle.zip
